// AUTO-GENERATED by tools/securitygen.py — do not edit by hand.
export const ACTIVE_KIND = {"wf:motion_sensor": "sensor", "wf:laser_tripwire": "tripwire", "wf:auto_turret": "turret", "wf:laser_emitter": "laser"};
export const DEVICE_ITEM = {"wf:motion_sensor_item": "wf:motion_sensor", "wf:laser_tripwire_item": "wf:laser_tripwire", "wf:auto_turret_item": "wf:auto_turret", "wf:laser_emitter_item": "wf:laser_emitter"};
export const BLOCK_COMPONENTS = ["wf:camera", "wf:monitor", "wf:door", "wf:keypad", "wf:siren", "wf:hub"];
export const SEC_BLOCKS = ["wf:security_camera", "wf:monitor", "wf:owner_door", "wf:keypad", "wf:floodlight", "wf:alarm_siren", "wf:control_hub"];
export const CAMERA_ID = "wf:security_camera";
export const KEYCARD = "wf:keycard";
