"""Wildforge pet roster — companions that go beyond vanilla cats/wolves.

plan:   quad | bird | reptile | turtle | blob | sprite   (drives the model)
size:   small (carry) | medium (follow) | large (ride)   (all teleport-follow)
combat: True -> defends owner, gains XP from kills, scales with level
fly:    True -> flying movement + fly animation
tier:   realistic | fantasy
"""

MEAT = ["minecraft:cooked_beef", "minecraft:beef"]
FISH = ["minecraft:cod", "minecraft:salmon"]
SEEDS = ["minecraft:wheat_seeds", "minecraft:melon_seeds"]
VEG = ["minecraft:carrot", "minecraft:dandelion"]
BUGS = ["minecraft:spider_eye"]

PETS = [
    # ---------------- realistic ----------------
    {"id": "dog", "name": "Dog", "plan": "quad", "size": "medium", "tier": "realistic",
     "food": MEAT, "health": 20, "scale": 0.9, "move": 0.32, "combat": True, "fly": False,
     "spawn": {"biome": "overworld", "bright": (7, 15), "weight": 6},
     "palette": {"body": "#9c7a4a", "belly": "#cbb085", "accent": "#5a4326", "eye": "#241a10",
                  "extra": "#3a2c18"},
     "features": {"ears": "floppy", "tail": "fluffy"}},
    {"id": "cat", "name": "Cat", "plan": "quad", "size": "small", "tier": "realistic",
     "food": FISH, "health": 12, "scale": 0.7, "move": 0.34, "combat": False, "fly": False,
     "spawn": {"biome": "overworld", "bright": (7, 15), "weight": 5},
     "palette": {"body": "#3a3a40", "belly": "#cfcfd6", "accent": "#1f1f24", "eye": "#9fe06a",
                  "extra": "#1a1a1f"},
     "features": {"ears": "pointy", "tail": "long"}},
    {"id": "rabbit", "name": "Rabbit", "plan": "quad", "size": "small", "tier": "realistic",
     "food": VEG, "health": 8, "scale": 0.6, "move": 0.36, "combat": False, "fly": False,
     "spawn": {"biome": "plains", "bright": (7, 15), "weight": 5},
     "palette": {"body": "#cab197", "belly": "#efe6d6", "accent": "#9a8467", "eye": "#7a3a2a",
                  "extra": "#b8a085"},
     "features": {"ears": "tall", "tail": "puff"}},
    {"id": "fox", "name": "Fox", "plan": "quad", "size": "medium", "tier": "realistic",
     "food": ["minecraft:sweet_berries", "minecraft:rabbit"], "health": 16, "scale": 0.8,
     "move": 0.36, "combat": True, "fly": False,
     "spawn": {"biome": "taiga", "bright": (7, 15), "weight": 4},
     "palette": {"body": "#c8722e", "belly": "#efe2d2", "accent": "#7a3a16", "eye": "#3a2410",
                  "extra": "#2a1810"},
     "features": {"ears": "pointy", "tail": "bushy"}},
    {"id": "ferret", "name": "Ferret", "plan": "quad", "size": "small", "tier": "realistic",
     "food": MEAT, "health": 10, "scale": 0.6, "move": 0.34, "combat": False, "fly": False,
     "spawn": {"biome": "forest", "bright": (7, 15), "weight": 3},
     "palette": {"body": "#d8c8a8", "belly": "#f2ead8", "accent": "#6a5436", "eye": "#2a1a10",
                  "extra": "#4a3a22"},
     "features": {"ears": "round", "tail": "long"}},
    {"id": "hamster", "name": "Hamster", "plan": "quad", "size": "small", "tier": "realistic",
     "food": SEEDS, "health": 6, "scale": 0.45, "move": 0.28, "combat": False, "fly": False,
     "spawn": {"biome": "plains", "bright": (7, 15), "weight": 3},
     "palette": {"body": "#e0b56a", "belly": "#f7ecd2", "accent": "#a87c3a", "eye": "#201810",
                  "extra": "#c89a4a"},
     "features": {"ears": "round", "tail": "stub"}},
    {"id": "parrot", "name": "Parrot", "plan": "bird", "size": "small", "tier": "realistic",
     "food": SEEDS, "health": 8, "scale": 0.7, "move": 0.3, "combat": False, "fly": True,
     "spawn": {"biome": "jungle", "bright": (7, 15), "weight": 4},
     "palette": {"body": "#d83a3a", "belly": "#f0c23a", "accent": "#2a6ad8", "eye": "#101010",
                  "extra": "#1aa84a"},
     "features": {"crest": True, "tail": "feathers"}},
    {"id": "gecko", "name": "Gecko", "plan": "reptile", "size": "small", "tier": "realistic",
     "food": BUGS, "health": 8, "scale": 0.55, "move": 0.26, "combat": False, "fly": False,
     "spawn": {"biome": "jungle", "bright": (7, 15), "weight": 3},
     "palette": {"body": "#5aa84a", "belly": "#cfe8a0", "accent": "#2f6a2a", "eye": "#f0c83a",
                  "extra": "#7ac84a"},
     "features": {"crest": False, "tail": "taper"}},
    {"id": "iguana", "name": "Iguana", "plan": "reptile", "size": "medium", "tier": "realistic",
     "food": VEG, "health": 16, "scale": 0.85, "move": 0.24, "combat": False, "fly": False,
     "spawn": {"biome": "desert", "bright": (7, 15), "weight": 3},
     "palette": {"body": "#7a9b5a", "belly": "#ccd9a8", "accent": "#4a6a32", "eye": "#d8a83a",
                  "extra": "#5a7a3a"},
     "features": {"crest": True, "tail": "taper"}},
    {"id": "turtle", "name": "Turtle", "plan": "turtle", "size": "medium", "tier": "realistic",
     "food": ["minecraft:seagrass", "minecraft:kelp"], "health": 20, "scale": 0.8, "move": 0.16,
     "combat": False, "fly": False,
     "spawn": {"biome": "beach", "bright": (7, 15), "weight": 3},
     "palette": {"body": "#4a7a5a", "belly": "#d8c89a", "accent": "#2f5a3a", "eye": "#2a1a10",
                  "extra": "#6a9a4a"},
     "features": {"shell": True, "tail": "stub"}},
    {"id": "capybara", "name": "Capybara", "plan": "quad", "size": "large", "tier": "realistic",
     "food": VEG, "health": 30, "scale": 1.2, "move": 0.24, "combat": False, "fly": False,
     "spawn": {"biome": "swamp", "bright": (7, 15), "weight": 3},
     "palette": {"body": "#8a6a44", "belly": "#b39468", "accent": "#5a4226", "eye": "#1a120a",
                  "extra": "#6a4f2e"},
     "features": {"ears": "round", "tail": "stub"}},
    {"id": "pony", "name": "Pony", "plan": "quad", "size": "large", "tier": "realistic",
     "food": ["minecraft:apple", "minecraft:hay_block"], "health": 28, "scale": 1.15, "move": 0.32,
     "combat": False, "fly": False,
     "spawn": {"biome": "plains", "bright": (7, 15), "weight": 3},
     "palette": {"body": "#a6794a", "belly": "#c8a06a", "accent": "#3a2a18", "eye": "#1a120a",
                  "extra": "#2a1d10"},
     "features": {"ears": "pointy", "tail": "hair", "mane": True}},
    {"id": "raptor_lizard", "name": "Riding Lizard", "plan": "reptile", "size": "large",
     "tier": "realistic", "food": MEAT, "health": 36, "scale": 1.25, "move": 0.34, "combat": True,
     "fly": False, "spawn": {"biome": "mesa", "bright": (7, 15), "weight": 2},
     "palette": {"body": "#7a5a3a", "belly": "#c8a86a", "accent": "#4a3422", "eye": "#e05a2a",
                  "extra": "#3a2a18"},
     "features": {"crest": True, "tail": "taper", "big_legs": True}},
    # ---------------- fantasy ----------------
    {"id": "slime_pet", "name": "Slime Pet", "plan": "blob", "size": "small", "tier": "fantasy",
     "food": ["minecraft:slime_ball"], "health": 12, "scale": 0.7, "move": 0.26, "combat": False,
     "fly": False, "spawn": {"biome": "swamp", "bright": (0, 15), "weight": 2},
     "palette": {"body": "#5ad06a", "belly": "#9af0a8", "accent": "#3aa84a", "eye": "#1a3a1a",
                  "extra": "#caffd0"},
     "features": {"tail": "none"}},
    {"id": "ember_sprite", "name": "Ember Sprite", "plan": "sprite", "size": "small",
     "tier": "fantasy", "food": ["minecraft:blaze_powder"], "health": 14, "scale": 0.6,
     "move": 0.3, "combat": True, "fly": True,
     "spawn": {"biome": "nether", "bright": (0, 15), "weight": 2},
     "palette": {"body": "#ff7a2a", "belly": "#ffd06a", "accent": "#d83a16", "eye": "#fff0a0",
                  "extra": "#ffae3a"},
     "features": {"flame": True, "tail": "none"}},
    {"id": "frost_sprite", "name": "Frost Sprite", "plan": "sprite", "size": "small",
     "tier": "fantasy", "food": ["minecraft:ice", "minecraft:snowball"], "health": 14,
     "scale": 0.6, "move": 0.3, "combat": True, "fly": True,
     "spawn": {"biome": "ice", "bright": (0, 15), "weight": 2},
     "palette": {"body": "#7ad0ff", "belly": "#dff4ff", "accent": "#3a8ad8", "eye": "#eaffff",
                  "extra": "#bfeaff"},
     "features": {"flame": True, "tail": "none"}},
    {"id": "mushroom_critter", "name": "Mushroom Critter", "plan": "quad", "size": "small",
     "tier": "fantasy", "food": ["minecraft:red_mushroom", "minecraft:brown_mushroom"],
     "health": 12, "scale": 0.6, "move": 0.24, "combat": False, "fly": False,
     "spawn": {"biome": "mushroom_island", "bright": (0, 15), "weight": 2},
     "palette": {"body": "#d8c0a0", "belly": "#efe2cf", "accent": "#d83a3a", "eye": "#2a1a10",
                  "extra": "#e8e8e8"},
     "features": {"ears": "round", "tail": "stub", "cap": True}},
    {"id": "cloud_pup", "name": "Cloud Pup", "plan": "quad", "size": "small", "tier": "fantasy",
     "food": ["minecraft:white_wool"], "health": 12, "scale": 0.7, "move": 0.3, "combat": False,
     "fly": True, "spawn": {"biome": "overworld", "bright": (12, 15), "weight": 2},
     "palette": {"body": "#eef2fa", "belly": "#ffffff", "accent": "#bcd0ea", "eye": "#5a7ad8",
                  "extra": "#dfe8f5"},
     "features": {"ears": "floppy", "tail": "puff", "wings": True}},
    {"id": "crystal_fox", "name": "Crystal Fox", "plan": "quad", "size": "medium",
     "tier": "fantasy", "food": ["minecraft:amethyst_shard"], "health": 20, "scale": 0.85,
     "move": 0.36, "combat": True, "fly": False,
     "spawn": {"biome": "the_end", "bright": (0, 15), "weight": 2},
     "palette": {"body": "#9a6ad8", "belly": "#e0cff5", "accent": "#6a3ac8", "eye": "#caff6a",
                  "extra": "#caa6ff"},
     "features": {"ears": "pointy", "tail": "crystal", "crystals": True}},
]

_ids = [p["id"] for p in PETS]
assert len(_ids) == len(set(_ids)), "duplicate pet id"
